// APP TEXT
const APP_TITLE = 'Pokemon APP';
const APP_DESCRIPTION = 'React TypeScript Material-UI';
// PAGES TITLE
const PAGE_TITLE_HOME = 'Home';
const PAGE_TITLE_PROFILE = 'Profile';
const PAGE_TITLE_POKEMON = 'Pokemon';

export { APP_TITLE, APP_DESCRIPTION, PAGE_TITLE_HOME, PAGE_TITLE_PROFILE, PAGE_TITLE_POKEMON };